### ISSUE TITLE
import gopool can not be found

### ISSUE THREAD

**Issue by zk101** [gobwas/ws-examples#1]
The two import references to gopool (main.go and chat.go) could not be found.  I had to update them to:
"github.com/gobwas/ws-examples/src/gopool"
To get the code to compile.  

Cheers
F

**Comment by gobwas** [comment]
Hi @zk101! Actually, all of the examples shall be built with `make` command. I use here the [gb](https://getgb.io/docs/usage/) directory structure convention (but not the gb itself). So to make it works you also must run `git submodule init && git submodule update` to fetch dependencies.

I will write notice in README.md now and make appropriate target in Makefile.

Thanks!

**Comment by zk101** [comment]
Clearly I didn't even look at the Makefile.

Thanks for your time.  

F
