### ISSUE TITLE
how to send ping/pong hearbeat

### ISSUE THREAD

**Issue by straysh** [gobwas/ws-examples#3]
I send 
```js
conn.send(JSON.stringify({
  id:     1,
  method: "ping",
  params: "ping",
}));
```

and the `header.OpCode` is `ws.OpText`(`0x1`)

how can I make ping/pong heartbeat then?

**Comment by gobwas** [comment]
Do you mean to send websocket ping/pong or your custom json-based ping/pong?

**Comment by gobwas** [comment]
For websocket based ping/pong you could make this:

```go
conn.Write(ws.CompiledPing)
...
conn.Write(ws.CompiledPong)
```

Note that `CompiledPing` is just result of:

```go
ping := ws.Frame{
    Header: ws.Header{
        Fin: true, 
        OpCode: ws.OpPing,
    },
}
var buf bytes.Buffer
ws.WriteFrame(&buf, ping)
CompiledPing := buf.Bytes()
```

**Comment by straysh** [comment]
probably I am making a mistake. I realized that I cannot make ping/pong frame on js client side.
But actually AS you'd mentioned, should send ping/pong payload over websocket.
So I closed the issue. Thank you!

**Comment by Smithx10** [comment]
I'm attempting to send ping/pong frames both in GoLang.  I'm confused if I should be attempting to use https://godoc.org/github.com/gobwas/ws/wsutil#ControlHandler.  The examples doesn't demonstrate this scenario and I think it would be a great addition.    

Using "Why use readData() for such case? Why not ReadMessage() or even ws.ReadHeader() and then handle frames manually?"  Should make this quite easy.
