### ISSUE TITLE
Add a license please 

### ISSUE THREAD

**Issue by darxtrix** [gobwas/ws-examples#6]
HI @gobwas , I would like to use a few examples in some OSS I am building. Would it possible for you to add a license so that I can make use of the code ?

I am mostly interested in the goroutine pool implementation https://github.com/gobwas/ws-examples/tree/master/src/gopool

Thanks !

**Comment by gobwas** [comment]
Hi @darxtrix!
Sorry for a such huge delay. Added license just now.
